// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file worker.proto (package worker, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatCompletionRequest, ChatCompletionResponse, HealthRequest, HealthResponse, ShutdownRequest, ShutdownResponse } from "./worker_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service worker.WorkerService
 */
export const WorkerService = {
  typeName: "worker.WorkerService",
  methods: {
    /**
     * Check health of the worker.
     *
     * @generated from rpc worker.WorkerService.Health
     */
    health: {
      name: "Health",
      I: HealthRequest,
      O: HealthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Shutdown the worker.
     *
     * @generated from rpc worker.WorkerService.Shutdown
     */
    shutdown: {
      name: "Shutdown",
      I: ShutdownRequest,
      O: ShutdownResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Generate text from a prompt. Only valid if worker is in inference mode.
     *
     * @generated from rpc worker.WorkerService.ChatCompletion
     */
    chatCompletion: {
      name: "ChatCompletion",
      I: ChatCompletionRequest,
      O: ChatCompletionResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

