# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import worker_pb2 as worker__pb2


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/worker.WorkerService/Health',
                request_serializer=worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=worker__pb2.HealthResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/worker.WorkerService/Shutdown',
                request_serializer=worker__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=worker__pb2.ShutdownResponse.FromString,
                )
        self.ChatCompletion = channel.unary_stream(
                '/worker.WorkerService/ChatCompletion',
                request_serializer=worker__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=worker__pb2.ChatCompletionResponse.FromString,
                )


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Check health of the worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown the worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatCompletion(self, request, context):
        """Generate text from a prompt. Only valid if worker is in inference mode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=worker__pb2.HealthRequest.FromString,
                    response_serializer=worker__pb2.HealthResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=worker__pb2.ShutdownRequest.FromString,
                    response_serializer=worker__pb2.ShutdownResponse.SerializeToString,
            ),
            'ChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=worker__pb2.ChatCompletionRequest.FromString,
                    response_serializer=worker__pb2.ChatCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/Health',
            worker__pb2.HealthRequest.SerializeToString,
            worker__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/Shutdown',
            worker__pb2.ShutdownRequest.SerializeToString,
            worker__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/worker.WorkerService/ChatCompletion',
            worker__pb2.ChatCompletionRequest.SerializeToString,
            worker__pb2.ChatCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
