# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\"\x0f\n\rHealthRequest\")\n\x0eHealthResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"\x11\n\x0fShutdownRequest\"\x12\n\x10ShutdownResponse\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\" \n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t*\x1e\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08STOPPING\x10\x01\x32\xaa\x01\n\rWorkerService\x12+\n\x06Health\x12\x0e.HealthRequest\x1a\x0f.HealthResponse\"\x00\x12\x31\n\x08Shutdown\x12\x10.ShutdownRequest\x1a\x11.ShutdownResponse\"\x00\x12\x39\n\x0eGenerateStream\x12\x10.GenerateRequest\x1a\x11.GenerateResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=184
  _STATUS._serialized_end=214
  _HEALTHREQUEST._serialized_start=16
  _HEALTHREQUEST._serialized_end=31
  _HEALTHRESPONSE._serialized_start=33
  _HEALTHRESPONSE._serialized_end=74
  _SHUTDOWNREQUEST._serialized_start=76
  _SHUTDOWNREQUEST._serialized_end=93
  _SHUTDOWNRESPONSE._serialized_start=95
  _SHUTDOWNRESPONSE._serialized_end=113
  _GENERATEREQUEST._serialized_start=115
  _GENERATEREQUEST._serialized_end=148
  _GENERATERESPONSE._serialized_start=150
  _GENERATERESPONSE._serialized_end=182
  _WORKERSERVICE._serialized_start=217
  _WORKERSERVICE._serialized_end=387
# @@protoc_insertion_point(module_scope)
