// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file manager.proto (package haven, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GenerateRequest, GenerateResponse } from "./manager_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service haven.Haven
 */
export const Haven = {
  typeName: "haven.Haven",
  methods: {
    /**
     * @generated from rpc haven.Haven.Generate
     */
    generate: {
      name: "Generate",
      I: GenerateRequest,
      O: GenerateResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

