// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file manager.proto (package haven, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, GenerateRequest, GenerateResponse, ListModelsResponse } from "./manager_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service haven.Haven
 */
export const Haven = {
  typeName: "haven.Haven",
  methods: {
    /**
     * Generate text from a prompt.
     *
     * @generated from rpc haven.Haven.Generate
     */
    generate: {
      name: "Generate",
      I: GenerateRequest,
      O: GenerateResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get the list of models and their descriptions.
     *
     * @generated from rpc haven.Haven.ListModels
     */
    listModels: {
      name: "ListModels",
      I: Empty,
      O: ListModelsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

